###########################
# Build the Spring Server #
###########################

FROM maven:3.8.6-openjdk-18 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
# RUN mvn -f /usr/src/app/pom.xml clean install -- Er kann wohl keinen clean install durchführen #


###################
# Run it with JDK #
###################

FROM openjdk:18-jdk-alpine
VOLUME /tmp
COPY --from=build /usr/src/app/target/* /usr/app/
# Hier sagt er, dass er den Pfad nicht findet?#
EXPOSE 8080
# ENTRYPOINT ["java","-jar","/usr/app/myBackend-0.0.1-SNAPSHOT.jar"] -- Wir haben noch keine Jar Datei? #