version: '2'

services:
  app:
    image: 'tippspiel:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: tippspiel
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sepdatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/sepdatabase


