version: '2'

services:

  app:
    image: 'tippspiel'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: tippspiel
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sepdatabase
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop


  db:
    image: 'postgres:14.5-alpine'
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=sepdatabase
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  frontend:
    image: client
    container_name: client
    build: ..\..\FrontEnd-AngularClient
    ports:
      - "4200:80"
    depends_on:
      - app


